ERROR - 2024-04-10 17:17:04 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\tu_taller\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\tu_taller\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', 'univalle', 'db_taller', 3306, '', 0)
#1 C:\xampp\htdocs\tu_taller\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\tu_taller\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\tu_taller\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT C.descri...', Array, false)
#4 C:\xampp\htdocs\tu_taller\app\Models\CitaModel.php(70): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tu_taller\app\Controllers\Cita.php(69): App\Models\CitaModel->SelectCitasCliente(NULL)
#6 C:\xampp\htdocs\tu_taller\system\CodeIgniter.php(904): App\Controllers\Cita->listaCitaCliente()
#7 C:\xampp\htdocs\tu_taller\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cita))
#8 C:\xampp\htdocs\tu_taller\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\tu_taller\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\tu_taller\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\tu_taller\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\tu_taller\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\tu_taller\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT C.descri...', Array, false)
#3 C:\xampp\htdocs\tu_taller\app\Models\CitaModel.php(70): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\tu_taller\app\Controllers\Cita.php(69): App\Models\CitaModel->SelectCitasCliente(NULL)
#5 C:\xampp\htdocs\tu_taller\system\CodeIgniter.php(904): App\Controllers\Cita->listaCitaCliente()
#6 C:\xampp\htdocs\tu_taller\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cita))
#7 C:\xampp\htdocs\tu_taller\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tu_taller\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-10 17:17:04 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT C.descripcion AS \'descripcionProblema\', C.fechaCita AS \'fechaCita\', C.estado AS \'estado\', S.descripcion AS \'servicio\', T.nombre AS \'taller\', C.idCita AS \'idCita\'
FROM `cita` `C`
INNER JOIN `servicio` `S` ON `S`.`idServicio` = `C`.`idServicio`
INNER JOIN `taller` `T` ON `T`.`idTaller` = `C`.`idTaller`
WHERE `C`.`idCliente` IS NULL', [], false)
 3 APPPATH\Models\CitaModel.php(70): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Cita.php(69): App\Models\CitaModel->SelectCitasCliente(null)
 5 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Cita->listaCitaCliente()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cita))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
